sudo: required

language: cpp

services:
 - docker

jobs:
  include:
    - name: basic_test
      script:
        - docker run  --interactive --tty pnikiel-cc7-quasar:latest /bin/bash -c "
            git clone --recursive -b nebula.B1 https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            git clone -b OPCUA-2081_CI_test_Poverty https://github.com/quasar-team/Poverty.git ;
            source Poverty/.CI/travis_test_script.sh ;
            "
